---
- name: Zero Trust Self
  hosts: all
  become: yes
  failed_when: false
  tasks:
  - name: Check if alread 0trusted
    stat:
      path: /etc/sudoers.d/ansible_zt
    register: ZT
  - name: Download 0trust sudo policy
    when: not ZT.stat.exists
    become: yes
    get_url:
      url: https://raw.githubusercontent.com{{ repository }}/{{ branch }}/sub_scripts/0trust/{{ inventory_hostname }}_zt
      dest: /etc/sudoers.d/ansible_zt
      mode: '0644'
  - name: Delete all permissive sudo
    when: not ZT.stat.exists
    become: yes
    file:
      path: /etc/sudoers.d/ansible
      state: absent

- name: Install Software
  hosts: all
  tasks:
  - name: Delete undeleted script
    file:
      path: /tmp/{{ inventory_hostname }}.install.sh
      state: absent
  - name: Download install script
    get_url:
      url: https://raw.githubusercontent.com{{ repository }}/{{ branch }}/sub_scripts/installations/{{ inventory_hostname }}.install.sh
      dest: /tmp/{{ inventory_hostname }}.install.sh
      mode: '0755'
  - name: Run install script
    shell: /tmp/{{ inventory_hostname }}.install.sh
    failed_when: false
    register: script_output
  - name: Delete script
    file:
      path: /tmp/{{ inventory_hostname }}.install.sh
      state: absent

- name: Config Software
  hosts: all
  tasks:
  - name: Delete undeleted script
    file:
      path: /tmp/{{ inventory_hostname }}.config.sh
      state: absent
  - name: Download config script
    get_url:
      url: https://raw.githubusercontent.com{{ repository }}/{{ branch }}/sub_scripts/configurations/{{ inventory_hostname }}.config.sh
      dest: /tmp/{{ inventory_hostname }}.config.sh
      mode: 0755
  - name: Run config script
    shell: /tmp/{{ inventory_hostname }}.config.sh
    failed_when: false
    register: script_output
  - name: Delete script
    file:
      path: /tmp/{{ inventory_hostname }}.config.sh
      state: absent
