- name: Config Jenkins
  hosts: cicd
  tasks:
  - name: Provide branch
    become: yes
    copy:
      content: "{{ branch }}"
      dest: /var/lib/jenkins/.branch
      mode: 0744
      owner: jenkins
      group: jenkins
  - name: Provide repository
    become: yes
    copy:
      content: "{{ repository }}"
      dest: /var/lib/jenkins/.repository
      mode: 0744
      owner: jenkins
      group: jenkins
  - name: Prepare caching
    become: yes
    file:
      path: /var/lib/jenkins/.cache_homeserver_build
      state: file
      mode: 0744
      owner: jenkins
      group: jenkins
  - name: Create .ssh folder
    become: yes
    file:
      path: /var/lib/jenkins/.ssh
      state: directory
      mode: 0700
      owner: jenkins
      group: jenkins
  - name: Provide id_rsa
    become: yes
    copy: 
      content: "{{ ssh_priv }}"
      dest: /var/lib/jenkins/.ssh/id_rsa
      mode: 0600
      owner: jenkins
      group: jenkins
  - name: Provide id_rsa.pub
    become: yes
    copy: 
      content: "{{ ssh_pub }}"
      dest: /var/lib/jenkins/.ssh/id_rsa.pub
      mode: 0600
      owner: jenkins
      group: jenkins
  - name: Create .tmp confidential folder
    become: yes
    file:
      path: /var/lib/jenkins/.tmp
      state: directory
      mode: 0700
      owner: jenkins
      group: jenkins
  - name: Provide proxmox.tfvars.json
    become: yes
    copy: 
      content: "{{ proxmox_config }}"
      dest: /var/lib/jenkins/.tmp/proxmox.tfvars.json
      mode: 0600
      owner: jenkins
      group: jenkins
  - name: Provide root_pwd
    become: yes
    copy: 
      content: "{{ root_pwd }}"
      dest: /var/lib/jenkins/.tmp/root.pwd
      mode: 0600
      owner: jenkins
      group: jenkins

  - name: Delete undeleted script
    file:
      path: /tmp/cicd.config.sh
      state: absent
  - name: Download config script
    get_url:
      url: https://raw.githubusercontent.com/llouu/homeserver/{{ branch }}/sub_scripts/configations/cicd.config.sh
      dest: /tmp/cicd.config.sh
      mode: 0755
  - name: Run config script
    shell: /tmp/cicd.config.sh
    failed_when: false
    register: script_output
  - name: Delete script
    file:
      path: /tmp/cicd.config.sh
      state: absent
  - name: Delete .tmp confidential folder
    become: yes
    file:
      path: /var/lib/jenkins/.tmp
      state: absent