---
pfsense:
   hosts:
      firewall: 
         ansible_host: 10.1.3.1
alpine:
   hosts:
      proxy: 
         ansible_host: 10.1.1.10
      reverse: 
         ansible_host: 10.1.2.20
      cicd: 
         ansible_host: 10.1.3.30
      iam: 
         ansible_host: 10.1.3.31
      pwdmgr: 
         ansible_host: 10.1.5.51
debian:
   hosts:
      proxmox:
         ansible_host: 10.1.3.10
      sunshine: 
         ansible_host: 10.1.4.41
      nas: 
         ansible_host: 10.1.5.50
ubuntu:
   hosts:
      siem: 
         ansible_host: 10.1.3.32
      kasm: 
         ansible_host: 10.1.4.40
all:
   children:
      pfsense:
      alpine:
      debian:
      ubuntu:
   vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
